#cloud-config
package_update: true
package_upgrade: true
packages:
  - software-properties-common
  - wget
  - curl
  - apache2
runcmd:
  - sudo apt-get install php php-cli php-common php-curl php-gd php-intl php-mbstring php-mysql php-readline php-xml php-xsl php-zip php-bz2 libapache2-mod-php -y
  - service apache2 restart

  # Install WordPress CLI
  - cd ~ 
  - sudo curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  - sudo chmod +x wp-cli.phar
  - sudo mv wp-cli.phar /usr/local/bin/wp

  # Set up WordPress
  - cd /var/www/
  - sudo chown -R www-data:www-data html
  - sudo chmod 755 html
  - cd html
  - sudo rm index.html
  - sudo -u www-data wp core download
  - sudo -u www-data wp core config --dbname='mydb' --dbuser='${rds_user}' --dbpass='${rds_pass}' --dbhost='${rds_endpoint}' --dbprefix='wp_'
  - sudo chmod -R 755 /var/www/html/wp-content

  # Install WordPress
  - sudo -u www-data wp core install --url='https://www.sarmadcloud.work' --title='My WordPress Website' --admin_user='${admin_username}' --admin_password='${admin_password}' --admin_email='${admin_emailaddress}'

  # Allow .htaccess files
  - sudo echo -e "<Directory /var/www/html>\n    AllowOverride All\n</Directory>" >> /etc/apache2/sites-enabled/allow-htaccess.conf
  - sudo a2enmod rewrite

  - echo "ok" | sudo tee /var/www/html/healthcheck.html
  - sudo chown www-data:www-data /var/www/html/healthcheck.html


  - sudo service apache2 restart